/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoc_game_Gui;

/**
 *
 * @author Fady
 */
public class GamePlayMenu extends javax.swing.JFrame {

    /**
     * Creates new form gamePlay
     */
    public GamePlayMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnOnePlayer = new javax.swing.JButton();
        btnTwoPlayers = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnOnline = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 40));

        btnOnePlayer.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnOnePlayer.setForeground(new java.awt.Color(255, 255, 255));
        btnOnePlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoc_game_Gui/Button1.png"))); // NOI18N
        btnOnePlayer.setText("Two Players");
        btnOnePlayer.setBorder(null);
        btnOnePlayer.setBorderPainted(false);
        btnOnePlayer.setContentAreaFilled(false);
        btnOnePlayer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOnePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnePlayerActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        btnTwoPlayers.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnTwoPlayers.setForeground(new java.awt.Color(255, 255, 255));
        btnTwoPlayers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoc_game_Gui/Button1.png"))); // NOI18N
        btnTwoPlayers.setText("Play With PC");
        btnTwoPlayers.setBorder(null);
        btnTwoPlayers.setBorderPainted(false);
        btnTwoPlayers.setContentAreaFilled(false);
        btnTwoPlayers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTwoPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoPlayersActionPerformed(evt);
            }
        });
        jPanel1.add(btnTwoPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/logout.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 50, 40));

        btnOnline.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btnOnline.setForeground(new java.awt.Color(255, 255, 255));
        btnOnline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoc_game_Gui/Button1.png"))); // NOI18N
        btnOnline.setText("Online With Friend");
        btnOnline.setBorder(null);
        btnOnline.setBorderPainted(false);
        btnOnline.setContentAreaFilled(false);
        btnOnline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnline, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoc_game_Gui/01.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/gameBoard.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTwoPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoPlayersActionPerformed
       ModePlayerOne twoplayer = new  ModePlayerOne();
                   twoplayer.setVisible(true);
                   twoplayer.pack();
                   twoplayer.setLocationRelativeTo(null);
                   this.dispose();
      
    }//GEN-LAST:event_btnTwoPlayersActionPerformed

    private void btnOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineActionPerformed
             OnlinePlayerGame game=new OnlinePlayerGame();
             game.setVisible(true);
                   game.pack();
                   game.setLocationRelativeTo(null);
                   this.dispose();
    }//GEN-LAST:event_btnOnlineActionPerformed

    private void btnOnePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnePlayerActionPerformed
         
       OnePlayerGame oneplayer = new OnePlayerGame();
                   oneplayer.setVisible(true);
                   oneplayer.pack();
                   oneplayer.setLocationRelativeTo(null);
                   this.dispose();
    }//GEN-LAST:event_btnOnePlayerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
   
       MainMenu mainmenu = new MainMenu();
                   mainmenu.setVisible(true);
                   mainmenu.pack();
                   mainmenu.setLocationRelativeTo(null);
                   this.dispose();
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginForm form=new LoginForm();
        form.setVisible(true);
                   form.pack();
                   form.setLocationRelativeTo(null);
                   this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlayMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOnePlayer;
    private javax.swing.JButton btnOnline;
    private javax.swing.JButton btnTwoPlayers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
