/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoc_game_Gui;

import OnlieClient.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 * 
 */

public class LoginForm extends javax.swing.JFrame {
    Client client; 
    public static String Username;
    public LoginForm() {
        initComponents();
      this.setLocationRelativeTo(null);//set screen on center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelmins = new javax.swing.JLabel();
        jTextusername = new javax.swing.JTextField();
        jPasswordpassword = new javax.swing.JPasswordField();
        jLabelclose = new javax.swing.JLabel();
        jButtonsignup = new javax.swing.JButton();
        jbtnlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 85, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UserName :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 89, -1));

        jLabelmins.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelmins.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmins.setText("-");
        jLabelmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminsMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 0, -1, -1));

        jTextusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextusername.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jTextusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 212, -1));

        jPasswordpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordpassword.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 212, -1));

        jLabelclose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelclose.setText("X");
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 0, -1, -1));

        jButtonsignup.setBackground(new java.awt.Color(192, 57, 43));
        jButtonsignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonsignup.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoc_game_Gui/Button1.png"))); // NOI18N
        jButtonsignup.setText("Sign Up");
        jButtonsignup.setBorder(null);
        jButtonsignup.setContentAreaFilled(false);
        jButtonsignup.setDefaultCapable(false);
        jButtonsignup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsignupActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 210, 31));

        jbtnlogin.setBackground(new java.awt.Color(34, 167, 240));
        jbtnlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnlogin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoc_game_Gui/Button1.png"))); // NOI18N
        jbtnlogin.setText("Login");
        jbtnlogin.setBorder(null);
        jbtnlogin.setBorderPainted(false);
        jbtnlogin.setContentAreaFilled(false);
        jbtnlogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnloginActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 210, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -10, 150, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoc_game_Gui/01.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminsMouseClicked
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelminsMouseClicked

    private void jbtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnloginActionPerformed
      if(verfyfields())
      {
        signin();
      
      }
    }//GEN-LAST:event_jbtnloginActionPerformed

    private void jPasswordpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordpasswordActionPerformed

    private void jButtonsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsignupActionPerformed
            SignUpForm form=new SignUpForm();
        form.setVisible(true);
                   form.pack();
                   form.setLocationRelativeTo(null);
                   this.dispose();
    }//GEN-LAST:event_jButtonsignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmins;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordpassword;
    private javax.swing.JTextField jTextusername;
    private javax.swing.JButton jbtnlogin;
    // End of variables declaration//GEN-END:variables

    public boolean verfyfields(){
    
    String username=jTextusername.getText().trim();
    String password=String.valueOf(jPasswordpassword.getPassword());
    
    if(username.trim().equals("")||password.trim().equals("") )
    {
        JOptionPane.showMessageDialog(null, "One or More filed is Empty");
    return false;
    }
    
    else return true;
}

    private void signin() {
        String username=jTextusername.getText().trim();
    String password =String.valueOf(jPasswordpassword.getPassword());
     Username=username;
        System.out.println("Connected!");

        try {
           
            client = Client.getClient();
            System.out.println("Sending string to the ServerSocket");

            client.sendMessage("IN." + username + "." + password);

            String message = client.readResponse();
            System.out.println("The message sent from the socket was: " + message);
           
            if (message.equalsIgnoreCase("Empty Field")) {

               JOptionPane.showMessageDialog(null,"Empty field enter the fields");
            
               
            } else if (message.equalsIgnoreCase("NOT FOUND")) {

                JOptionPane.showMessageDialog(null,"password or user is invalid");
                
            } else if (message.equalsIgnoreCase("NOT Valid Name")) {
               JOptionPane.showMessageDialog(null," user is invalid");

            } else if (message.equalsIgnoreCase("NOT Valid Pass")) {
               JOptionPane.showMessageDialog(null,"password is not valid");

            } else if (!message.equalsIgnoreCase("NOT FOUND") && !message.equalsIgnoreCase("NO ENTRY")&&
                !message.equalsIgnoreCase("NOT Valid Name") && !message.equalsIgnoreCase("NOT Valid Pass") && message.equalsIgnoreCase("sign in Succeeded")
                    &&!jTextusername.getText().startsWith(" ")&&!password.startsWith(" ")) 
            {
                System.out.println("Login");
                 JOptionPane.showMessageDialog(null, "suceced ");
                
                 
                MainMenu menu =new MainMenu();
                  menu.setVisible(true);
                   menu.pack();
                   menu.setLocationRelativeTo(null);
                 this.dispose();

                
            }
            else{
             JOptionPane.showMessageDialog(null, "Erorr");
            
            }
            

    }   catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            client.closeClient();
        }
    }
}
