/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoc_game_Gui;

import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author asus
 */

public class ShowGamesingle extends javax.swing.JFrame {
Icon x_icon;
Icon o_icon;
    /**
     * Creates new form ShowGamelocal
     */
    
    JButton [] btn = new JButton[9];
    public ShowGamesingle() {
        initComponents();
         btn[0] = jbtn0;
        btn[1] = jbtn1;
        btn[2] = jbtn2;
        btn[3] = jbtn3;
        btn[4] = jbtn4;
        btn[5] = jbtn5;
        btn[6] = jbtn6;
        btn[7] = jbtn7;
        btn[8] = jbtn8;
        x_icon = new ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\TicTacToc_Game\\src\\ui\\xIcon.png", "x");
        o_icon = new ImageIcon("C:\\Users\\asus\\Documents\\NetBeansProjects\\TicTacToc_Game\\src\\ui\\oIcon.png", "o");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public void showdata(String data, String local)
    {
        
        String FilegameDate;
        String FilePlayerName1;
        String FilePlayerScore1;
        String FilePlayerName2;
        String FilePlayerScore2;
        String FileWinner;
        System.out.println("data\n" +data);
        int btn1;
        System.out.println("inside showdata" );
        String value;
        LinkedHashMap<Integer, String> moves = new LinkedHashMap<>();
        String[] splitline = local.split("/n");
        
        for(int x = 0; x<splitline.length; x++)
        {
            
            String [] line = splitline[x].split(",");
            FilegameDate = line[0];
            System.out.println("data\n" +data);
            if(FilegameDate.equalsIgnoreCase(data))
            {
                System.out.println("inside FilegameDate\n" +FilegameDate);
                FilePlayerName1 = line[1];
                FilePlayerScore1 = line[2];
                FilePlayerName2 = line[3];
                FilePlayerScore2 = line[4];
                jplayer1.setText(FilePlayerName1);
                jplayer2.setText(FilePlayerName2);
                jscore1.setText(FilePlayerScore1);
                jscore2.setText(FilePlayerScore2);
                System.out.println("result in line 5"+line[5]);
                FileWinner = line[5];
                
                for (int j = 6, k = 7; j < line.length  && k < line.length ; j += 2, k += 2) {
                    btn1 = Integer.parseInt(line[j]);
                    value = line[k];
                    moves.put(btn1, value);
                    System.out.println("aaaaaaaaaaaaaaaaaaaaaaaaaaaa" + btn1 + "/" + value);

                }
                
            }
            System.out.println("out side for loop");
            Thread n = new Thread(new Runnable() {
                @Override
                public void run() {
                    
                
                for (int key:moves.keySet())
                {
                    try {
                        if(moves.get(key).equals("X"))
                         btn[key].setIcon(x_icon);
                        else if(moves.get(key).equals("O"))
                           btn[key].setIcon(o_icon);  
                       
                        
                        Thread.sleep(1000);
                       
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ShowGamesingle.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            
                }
            });
            
            n.start();
            
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jplayer1 = new javax.swing.JLabel();
        jscore1 = new javax.swing.JLabel();
        jplayer2 = new javax.swing.JLabel();
        jscore2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn0.setForeground(new java.awt.Color(255, 255, 255));
        jbtn0.setBorder(null);
        jbtn0.setBorderPainted(false);
        jbtn0.setContentAreaFilled(false);
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 80));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn1.setForeground(new java.awt.Color(255, 255, 255));
        jbtn1.setBorder(null);
        jbtn1.setBorderPainted(false);
        jbtn1.setContentAreaFilled(false);
        jPanel1.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, 80));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn2.setBorder(null);
        jbtn2.setBorderPainted(false);
        jbtn2.setContentAreaFilled(false);
        jPanel1.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 120, 90));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn3.setForeground(new java.awt.Color(255, 255, 255));
        jbtn3.setBorder(null);
        jbtn3.setBorderPainted(false);
        jbtn3.setContentAreaFilled(false);
        jPanel1.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 130));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn4.setForeground(new java.awt.Color(255, 255, 255));
        jbtn4.setBorder(null);
        jbtn4.setBorderPainted(false);
        jbtn4.setContentAreaFilled(false);
        jPanel1.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 150, 120));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn5.setForeground(new java.awt.Color(255, 255, 255));
        jbtn5.setBorder(null);
        jbtn5.setBorderPainted(false);
        jbtn5.setContentAreaFilled(false);
        jPanel1.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 110, 120));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn6.setForeground(new java.awt.Color(255, 255, 255));
        jbtn6.setBorder(null);
        jbtn6.setBorderPainted(false);
        jbtn6.setContentAreaFilled(false);
        jPanel1.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 110, 110));

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn7.setForeground(new java.awt.Color(255, 255, 255));
        jbtn7.setBorder(null);
        jbtn7.setBorderPainted(false);
        jbtn7.setContentAreaFilled(false);
        jPanel1.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 140, 110));

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn8.setForeground(new java.awt.Color(255, 255, 255));
        jbtn8.setBorder(null);
        jbtn8.setBorderPainted(false);
        jbtn8.setContentAreaFilled(false);
        jPanel1.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 120, 110));

        jplayer1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jplayer1.setForeground(new java.awt.Color(255, 255, 255));
        jplayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/user.png"))); // NOI18N
        jplayer1.setText("Player 1");
        jPanel1.add(jplayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 50));

        jscore1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jscore1.setForeground(new java.awt.Color(255, 255, 255));
        jscore1.setText(" 0");
        jPanel1.add(jscore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 40, -1));

        jplayer2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jplayer2.setForeground(new java.awt.Color(255, 255, 255));
        jplayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/user.png"))); // NOI18N
        jplayer2.setText("Player 2");
        jPanel1.add(jplayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 140, 50));

        jscore2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jscore2.setForeground(new java.awt.Color(255, 255, 255));
        jscore2.setText("0");
        jPanel1.add(jscore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 40, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/VS.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/gameBoard.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        ModePlayerOne gamemainmenu = new ModePlayerOne();
        gamemainmenu.setVisible(true);
        gamemainmenu.pack();
        gamemainmenu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowGamesingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowGamesingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowGamesingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowGamesingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowGamesingle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JLabel jplayer1;
    private javax.swing.JLabel jplayer2;
    private javax.swing.JLabel jscore1;
    private javax.swing.JLabel jscore2;
    // End of variables declaration//GEN-END:variables
}
